[workspace]
resolver = "3"

members = [
  "ra4m1-ctpac",
  "ra4-hal",
  "ra4-examples",
  "uno-r4wifi-bsc",
]

exclude = [
]

[workspace.dependencies]
cortex-m = { version = "0.7.7", features = [ "inline-asm", "critical-section-single-core" ] }
cortex-m-rt = { version = "0.7.3" }
critical-section = { version = "1.2" }
defmt = { version = "1" }
panic-halt = "0.2.0"
embassy-hal-internal = { version = "0.4.0", features = ["cortex-m", "prio-bits-4"] }
embassy-sync = { version = "0.7.2" }
embassy-time = { version = "0.5.0" }
embedded-io = { version = "0.6.1" }
embedded-io-async = { version = "0.6.1" }
embedded-serial= { version = "0.5.0" }

[profile.release]
opt-level = "z"
