# Abuse this to add things in a case sensitive manner
ignore_patterns = [
    '[A-Z]{2,}',
    'IEL',
    'BSP',
    'ICK',
    'FCK',
    'OFS[01]',
    'SCE[59]',
    '((Crc)?Ccit|CCIT)',
    '(hoco|loco|moco|ofs|sce|ick|fck)(_|\d+)',
    'Sce',
    '\w+-bsc',
    '=-T.+',
    '=--nmagic',
    '\.(ick|fck)',
    'vergen_[a-z0-9]+',
    '[Uu]hh+',
    'thumbv[678]em-none-eabi(hf)?',
    '[A-Z][A-Za-z0-9_]+\d+Mhz',
]
ignore_paths = ["target/**/*", "**/*.json", ".git/**/*", "**/*.hex"]
use_global = false
words = [
    "arduinos",
    "chiptool",
    "defmt",
    "microcontroller",
    "microcontrollers",
    "pfs",
    "programmatically",
    "renesas",
    "pcka",
    "pckb",
    "pckc",
    "pckd",
    "fmifrt",
    "memwait",
    "hococr",
    "mcu",
    "iclk",
    "uart",
    "sckdivcr",
    "chrono",
    "Clk",
    "waker",
    "getc",
    "putc",
    "hoco",
    "loco",
    "moco",
    "usb",
    "vergen",
    "pll",
    "vbatt",
    "pwm",
    "irqs",
    "ihex",
    "isel",
    "accessors",
    "iota",
    "mstp",
    "ctpac",
    "ielsr",
    "rcksel",
    "prkey",
    "clippy",
    "objdump",
    "uno",
    "pfunc",
    "gpio",
    "rodata",
    "agt",
    "vref",
    "nmos",
    "brme",
    "scmr",
    "mddr",
    "psel",
    "pidr",
    "pmr",
    "dscr",
    "porr",
    "posr",
    "eidr",
    "pdr",
    "pcntr",
    "hcstp",
    "spbyt",
    "bysw",
    "spcdr",
    "dmac",
    "typelevel",
    "iic",
    "fieldsets",
    "vdsel",
    "lvdas",
    "prio",
    "asel",
    "mpu",
    "kint",
    "gpt",
    "mosc",
    "cksel",
    "sosc",
    "cstrt",
    "HCFRQ",
    "HOCOFRQ",
    "podr",
    "rtc",
    "ssie",
    "ctsu",
    "wdt",
    "iwdt",
    "rtt",
    "ofsdump",
    "aadje",
    "aadjp",
    "pmisc",
    "adc",
    "dtce",
    "gpreg",
    "dtc",
    "smr",
    # "lms",
]
