words = [
    "aadje",
    "aadjp",
    "accessors",
    "adc",
    "agt",
    "arduinos",
    "asel",
    "baudrate",
    "binutils",
    "brdv",
    "brme",
    "bysw",
    "chiptool",
    "chrono",
    "cksel",
    "clippy",
    "clk",
    "cstrt",
    "ctpac",
    "ctsu",
    "defmt",
    "direnv",
    "dmac",
    "dscr",
    "dtc",
    "dtce",
    "eidr",
    "elc",
    "fcache",
    "fieldsets",
    "fmifrt",
    "getc",
    "gpio",
    "gpreg",
    "gpt",
    "gsed",
    "hcfrq",
    "hcfrqw",
    "hcstp",
    "hoco",
    "hococr",
    "hocofrq",
    "iclk",
    "ielsr",
    "ihex",
    "iic",
    "impls",
    "iota",
    "irqs",
    "isel",
    "iwdt",
    "kint",
    "libm",
    "lms",
    "loco",
    "lvdas",
    "mcu",
    "mddr",
    "memwait",
    "microcontroller",
    "microcontrollers",
    "micromath",
    "moco",
    "mosc",
    "mosi",
    "mpu",
    "mstp",
    "mstpcr",
    "nmi",
    "nmos",
    "objdump",
    "ofsdump",
    "osm",
    "pcntr",
    "pdr",
    "pfs",
    "pfunc",
    "pidr",
    "pinmap",
    "pll",
    "pmisc",
    "pmr",
    "podr",
    "popd",
    "porr",
    "posr",
    "prescaler",
    "prio",
    "prkey",
    "programmatically",
    "psel",
    "pushd",
    "putc",
    "pwm",
    "rcksel",
    "renesas",
    "rodata",
    "rtc",
    "rtt",
    "rvm",
    "sck",
    "sckdivcr",
    "scl",
    "scmr",
    "sda",
    "sed",
    "smr",
    "sosc",
    "spbr",
    "spbyt",
    "spcdr",
    "ssie",
    "typelevel",
    "uart",
    "underflows",
    "uno",
    "usb",
    "vbatt",
    "vdsel",
    "vergen",
    "vref",
    "waker",
    "wdt",
    "zepeda",
    "µs",
]
ignore_paths = [
    "target/**/*",
    "**/*.json",
    ".git/**/*",
    "**/*.hex",
]
ignore_patterns = [
    "[A-Z]{2,}",
    "[A-Z]{2,}[n0-9]+",
    "((Crc)?Ccit|CCIT)",
    '(hoco|loco|moco|ofs|sce|ick|fck)(_|\d+)',
    "Sce",
    '\w+-bsc',
    "=-T.+",
    "=--nmagic",
    '\.(ick|fck)',
    "vergen_[a-z0-9]+",
    "[Uu]hh+",
    "thumbv[678]em-none-eabi(hf)?",
    '[A-Z][A-Za-z0-9_]+\d+Mhz',
    "0x[0-9a-fA-F]{1,3}",
    "0x([0-9a-fA-F]{4}_?)+",
    'elf(32|64)-\w+',
    "Ofs[01]",
    "MSTP[ABCD](n)+",
    "asm::(nop)",
    "iccr[12]",
    "Vcc",
    '\w+_pin_impl',
    'FSP_Packs_v\d.\d.\d.zip',
    "T(low|high)",
    'swd-.\w+',
    "_c[tr]x",
    'regs\(\)',
    "skip-osm",
    "(Msb|Lsb)First",
    "- osm",
    "ElcSw[eE]vt[01]",
    "Avcc",
    "Vref(h?)",
    "pcl?k[abcd]",
    "PCL?K[ABCD]",
    "Ccmp[AB]",
    "Cmp[CDEF]",
    "ccmp[ab]",
    "cmp[cdef]",
    "Udf",
    "Ovf",
]
use_global = false
