words = [
    "aadje",
    "aadjp",
    "accessors",
    "adc",
    "agt",
    "arduinos",
    "asel",
    "brme",
    "bysw",
    "chiptool",
    "chrono",
    "cksel",
    "clippy",
    "clk",
    "cstrt",
    "ctpac",
    "ctsu",
    "defmt",
    "dmac",
    "dscr",
    "dtc",
    "dtce",
    "eidr",
    "fieldsets",
    "fmifrt",
    "getc",
    "gpio",
    "gpreg",
    "gpt",
    "hcfrq",
    "hcstp",
    "hoco",
    "hococr",
    "hocofrq",
    "iclk",
    "ielsr",
    "ihex",
    "iic",
    "impls",
    "iota",
    "irqs",
    "isel",
    "iwdt",
    "kint",
    "lms",
    "loco",
    "lvdas",
    "mcu",
    "mddr",
    "memwait",
    "microcontroller",
    "microcontrollers",
    "moco",
    "mosc",
    "mpu",
    "mstp",
    "nmos",
    "objdump",
    "ofsdump",
    "pcka",
    "pckb",
    "pckc",
    "pckd",
    "pcntr",
    "pdr",
    "pfs",
    "pfunc",
    "pidr",
    "pinmap",
    "pll",
    "pmisc",
    "pmr",
    "podr",
    "popd",
    "porr",
    "posr",
    "prio",
    "prkey",
    "programmatically",
    "psel",
    "pushd",
    "putc",
    "pwm",
    "rcksel",
    "renesas",
    "rodata",
    "rtc",
    "rtt",
    "sckdivcr",
    "scmr",
    "smr",
    "sosc",
    "spbyt",
    "spcdr",
    "ssie",
    "typelevel",
    "uart",
    "uno",
    "usb",
    "vbatt",
    "vdsel",
    "vergen",
    "vref",
    "waker",
    "wdt",
]
ignore_paths = [
    "target/**/*",
    "**/*.json",
    ".git/**/*",
    "**/*.hex",
]
ignore_patterns = [
    "[A-Z]{2,}",
    "IEL",
    "BSP",
    "ICK",
    "FCK",
    "OFS[01]",
    "SCE[59]",
    "((Crc)?Ccit|CCIT)",
    '(hoco|loco|moco|ofs|sce|ick|fck)(_|\d+)',
    "Sce",
    '\w+-bsc',
    "=-T.+",
    "=--nmagic",
    '\.(ick|fck)',
    "vergen_[a-z0-9]+",
    "[Uu]hh+",
    "thumbv[678]em-none-eabi(hf)?",
    '[A-Z][A-Za-z0-9_]+\d+Mhz',
]
use_global = false
