[package]
name = "ra4-hal"
version = "0.1.4-dev"
edition = "2024"
rust-version = "1.91"
description = "Hardware Abstraction Layer (HAL) for the Renesas RA4 family of MCUs."
homepage = "https://sr.ht/~az1/ra4m1-rs/"
license = "LGPL-3.0-or-later"

[dependencies]
defmt = { workspace = true, optional = true }
cortex-m = { workspace = true }
cortex-m-rt = { workspace = true }
critical-section = { workspace = true }

embedded-hal-1 = { package = "embedded-hal", version = "1.0" }

embassy-hal-internal = { version = "0.3.0", features = ["cortex-m", "prio-bits-4"] }
embassy-time = { workspace = true, optional = true }
embassy-time-driver = { version = "0.2.1", optional = true }
embassy-time-queue-utils = { version = "0.3.0", optional = true }
embassy-usb-driver = { version = "0.2.0", optional = true }
embassy-sync = { workspace = true }

ra4m1-ctpac = { path = "../ra4m1-ctpac" }

cfg-if = "1"

[features]
default = [ "defmt", "time-driver", "rt", "uno_r4" ]

# Enable the `rt` feature of the PAC.
# With `rt` enabled the PAC provides interrupt vectors instead of letting [`cortex-m-rt`](https://docs.rs/cortex-m-rt) do that.
# See <https://docs.rs/cortex-m-rt/latest/cortex_m_rt/#device> for more info.
rt = [ "ra4m1-ctpac/rt" ]

defmt = [ "dep:defmt", "ra4m1-ctpac/defmt" ]
time-driver = [ "dep:embassy-time-driver", "dep:embassy-time-queue-utils", "embassy-time-driver/tick-hz-48_000_000" ]
unstable-pac = [ ]

### Board features
uno_r4 = [ "_64pin" ]

### Internal use only
_48pin = [ ]
_64pin = [ ]
_100pin = [ ]

[package.metadata.docs.rs]
default-target = "thumbv7em-none-eabihf"
