[package]
name = "ra4m1-ctpac"
version = "0.1.8-dev"
authors = ["Alex Zepeda <srht@inferiorhumanorgans.com>"]
edition = "2024"
rust-version = "1.91"
description = "Peripheral Access Crate (PAC) for the Renesas RA4M1."
homepage = "https://sr.ht/~az1/ra4m1-rs/"
license = "LGPL-3.0-or-later"

[dependencies]
defmt = { workspace = true, optional = true }
cortex-m = { workspace = true }
cortex-m-rt = { workspace = true }
critical-section = { workspace = true }

[features]
defmt = ["dep:defmt"]
rt = ["cortex-m-rt/device"]

[package.metadata.docs.rs]
default-target = "thumbv7em-none-eabihf"
