[package]
name = "ra4-examples"
version = "0.1.0-dev"
edition = "2024"
license = "LGPL-3.0-or-later"
description = "HAL examples for the Renesas RA4 family of MCUs."

[dependencies]
## Core dependencies
cortex-m = { workspace = true }
cortex-m-rt = { workspace = true }
defmt = { workspace = true }
defmt-rtt = "1.0.0"
panic-probe = { version = "1.0.0" }

## Embassy dependencies
# embassy-embedded-hal = { version = "0.5.0", default-features = false }
embassy-executor = { version = "0.9.0", features = [ "arch-cortex-m", "executor-thread", "executor-interrupt" ] }
embassy-time = { workspace = true }
# embassy-futures = { version = "0.1.2" }

## Board stuff
ra4-hal = { path = "../ra4-hal", features = [ "unstable-pac" ] }

## Third party stuff
atomic_float = { version = "1.1.0" }
heapless = { version = "0.9.2" }

## For the I2C example
# embedded-graphics = { version = "0.8.1" }
# ssd1306 = { version = "0.10.0" }

[build-dependencies]
vergen-gitcl = { version = "1.0.8" }

[features]
default = [ "defmt" ]
defmt = [ "panic-probe/print-defmt", "embassy-executor/defmt", "embassy-time/defmt", "embassy-time/defmt-timestamp-uptime" ]
