# https://doc.rust-lang.org/nightly/cargo/reference/config.html#including-extra-configuration-files
include = [
  { path = "../cargo-config.toml", optional = true }
]

[target.'cfg(all(target_arch = "arm", target_os = "none"))']
# If autodetection fails, update your probe-rs to 0.32 or newer (or use from git)
runner = "probe-rs run"

[alias]
dup = [ "tree", "-f", "{p} {f}", "-d" ]
clip = [ "clippy", "--quiet", "--no-deps", "--workspace" ]
haldoc = [ "doc", "--no-deps", "-p", "ra-hal" ]

[env]
DEFMT_LOG = "debug"
