[workspace]
resolver = "3"

members = [
  "ra2a1",
  "ra4l1",
  "ra4l1-rtic",
  "ra4m1",
  "ra6m5",
  "ra8m1",
]

exclude = [
]

[workspace.package]
authors = ["Alex Zepeda <srht@inferiorhumanorgans.com>"]
edition = "2024"
rust-version = "1.95"
license = "LGPL-3.0-or-later"
homepage = "https://sr.ht/~az1/ra-rs/"
version = "0.3.0-dev"

[workspace.dependencies]
assign-resources = { version = "0.5.0" }
cortex-m = { version = "0.7.7", features = [ "inline-asm", "critical-section-single-core" ] }
cortex-m-rt = { version = "0.7.3" }
critical-section = { version = "1.2" }
defmt = { version = "1" }
defmt-rtt = { version = "1.0.0" }
document-features = { version = "0.2.12" }
embassy-executor = { version = "0.10.0", features = [ "platform-cortex-m", "executor-thread", "executor-interrupt" ] }
embassy-futures = { version = "0.1.2" }
embassy-hal-internal = { version = "0.5.0", features = [ "cortex-m", "prio-bits-4" ] }
embassy-sync = { version = "0.8.0" }
embassy-time = { version = "0.5.1" }
embassy-time-driver = { version = "0.2.2" }
embassy-time-queue-utils = { version = "0.3.0" }
embassy-usb-driver = { version = "0.2.0" }
embedded-hal-1 = { package = "embedded-hal", version = "1.0" }
embedded-hal-async = { version = "1.0" }
embedded-io = { version = "0.6.1" }
embedded-io-async = { version = "0.6.1" }
embedded-serial = { version = "0.5.0" }
micromath = { version = "2.1" }
libm = { version = "0.2.16" }
panic-probe = { version = "1.0.0" }
ra-hal = { path = "../ra-hal" }

[profile.release]
opt-level = "z"
debug = 2
overflow-checks = true

[profile.release.package."*"]
opt-level = "z"
debug = 2
overflow-checks = true

[profile.dev]
opt-level = "z"

[profile.dev.package."*"]
opt-level = "z"

